name: Motor Maven Publish Workflow

on:
  repository_dispatch:
    types: [new-android-framework]

jobs:
  publish-package:
    name: "Publish Android Package to Github Maven Package"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACTIONS_GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download Latest Android Release
        run: gh release download -R sonr-io/sonr -p 'motorlib_*_android_*.tar.gz'
